name: Publish docs via GitHub Pages
on:
  push:

jobs:
  build_artefact_pdf:
    name: Build and artefact PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install requirements with PDF
        run: pip install -r requirements.txt -r pdf_requirements.txt
      - name: Inject plugin
        run: sed -i 's/#  - with-pdf/  - with-pdf/' mkdocs.yml 
      - name: Create PDF
        run: mkdocs build
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: site/pdf/document.pdf
